"""The model and the manifest, as a pair. The second half is not optional.

A GENERATED MODEL IS OUTPUT, and nothing else proofreads it. The manifest is
what makes that output auditable: every account the register carried and the
model does not is named here with a reason, so *excluded* and *forgotten* are
different words rather than the same silence. Without it a model that dropped
half the book looks exactly like a model of half a book.

ONE ENTITY TYPE FOR THE WHOLE BOOK. Every account is an `Account`, and the
requirement each one is held to is read off the entity through
`{from_property: margin_requirement}`. Until that existed, a declared bound
lived on the entity TYPE and a book of four hundred accounts with four hundred
requirements meant four hundred types -- a model with one type per instance has
stopped being a model.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Mapping, Sequence, Tuple

from .records import Account

#: The type name for a forecaster entity. IT IS THIS PACKAGE'S WORD. The engine
#: takes it as an argument and contains no such name anywhere, because a type
#: name compiled into a domain-free core would be a domain word in the one place
#: the project refuses to put one.
FORECASTER_TYPE = "ForecastModel"

EXCLUDED_NOT_EXPECTED = "register says no forecast is expected for this account"
EXCLUDED_NO_REQUIREMENT = (
    "register carried no margin_requirement, so the declared floor has nothing "
    "to read and BOUNDEDNESS would decline no_threshold on every cycle")


@dataclass(frozen=True)
class Manifest:
    """What the model leaves out, and why. Ordered so two runs compare."""

    excluded: Tuple[Tuple[str, str], ...]
    included: Tuple[str, ...]

    def as_dict(self) -> Dict[str, object]:
        return {
            "included": list(self.included),
            "excluded": [{"account_id": a, "reason": r} for a, r in self.excluded],
            "counts": {"included": len(self.included), "excluded": len(self.excluded)},
        }


def partition(accounts: Sequence[Account]) -> Manifest:
    included: List[str] = []
    excluded: List[Tuple[str, str]] = []
    for account in accounts:
        if not account.forecast_expected:
            excluded.append((account.account_id, EXCLUDED_NOT_EXPECTED))
        elif account.requirement is None:
            excluded.append((account.account_id, EXCLUDED_NO_REQUIREMENT))
        else:
            included.append(account.account_id)
    return Manifest(tuple(sorted(excluded)), tuple(sorted(included)))


def build_model(models: Sequence[str] = (), *, max_age: str = "15m",
                report_above: float = 0.25) -> str:
    """The domain YAML this bridge feeds.

    `models:` and `max_age:` are declared only when the caller supplies them,
    which is the engine's rule carried through rather than reinvented: without
    `models:` no id is unknown, because refusing every id the engine has not
    seen would refuse the first forecast any producer ever sends.
    """
    declared = ""
    if models:
        declared = "\n          models: [" + ", ".join(sorted(models)) + "]"
    return f"""# GENERATED by margin-book-audit. Read it back through model_describe
# before trusting it; nothing else proofreads a generated model.
domain:
  id: margin-book
  name: Client Margin Book
  entity_types: [Account, {FORECASTER_TYPE}]
  relationship_types: []
  indicators:
    Account:
      - name: margin_balance
        type: NUMERIC
        axioms: [BOUNDEDNESS]
        lower_critical: {{from_property: margin_requirement}}
        window: 1h
        forecast:
          expected: true{declared}
          max_age: {max_age}
        dynamics:
          model: local_level
          report_above: {report_above}
        horizon: 1h
        lookback: 7d
      - name: margin_requirement
        type: NUMERIC
        axioms: []
    {FORECASTER_TYPE}:
      - name: forecasts_expected
        type: NUMERIC
        axioms: [CONSERVATION]
        window: 24h
        flow: in
        conservation:
          input_property: forecasts_expected
          output_properties: [forecasts_issued]
          loss_margin: 0
      - name: forecasts_issued
        type: NUMERIC
        axioms: []
        flow: out
      - name: coverage_90
        type: NUMERIC
        axioms: [HOMEOSTASIS]
        window: 7d
        homeostasis: {{setpoint: 0.90, tolerance: 0.05}}
      - name: pinball_loss
        type: NUMERIC
        axioms: [HOMEOSTASIS]
        window: 7d
      - name: graded_n
        type: NUMERIC
        axioms: [MONOTONICITY]
        window: 7d
        monotonicity: {{expected_direction: increasing, allow_reset: true}}
      - name: forecast_age_s
        type: NUMERIC
        role: latency
        axioms: [RESPONSIVENESS]
        warning: 900
        critical: 1800
        window: 6h
"""


#: The keys `model_describe` must carry for a read-back to mean anything. They
#: live under `model`, NOT at the top of the payload -- the first version of
#: this function read them from the top, found nothing, and returned three empty
#: lists on every call. An empty list reads as *nothing wrong*, so a guard aimed
#: at the wrong level is not a weak guard: it is no guard that reports success,
#: and four tests asserting `== []` passed against it.
PROOF_KEYS = ("unreachable_declarations", "unread_fields")


class ModelUnreadable(LookupError):
    """`model_describe` did not carry the keys a read-back needs."""


def read_back(session: object) -> Dict[str, object]:
    """Proofread a generated model through the engine, not by eye.

    NOTHING ELSE PROOFREADS AN OUTPUT. `build_model` interpolates, and an
    interpolation that lands at the wrong indentation produces a document that
    is still YAML-shaped -- the first version put `models:` two columns short
    and the loader raised eight lines below the mistake. Worse is the version
    that LOADS: a declaration the engine cannot reach is never evaluated, and a
    check nobody runs looks exactly like a check that found nothing.

    Raises `ModelUnreadable` when the envelope does not carry the keys, rather
    than returning an empty result. A proofreader that cannot find the page must
    not report a clean page.
    """
    from arbiter_engine.api import model_describe

    envelope = model_describe(session)
    raw = envelope.to_dict() if hasattr(envelope, "to_dict") else envelope
    payload = raw.get("payload") if isinstance(raw.get("payload"), dict) else raw
    model = payload.get("model")
    if not isinstance(model, dict):
        raise ModelUnreadable(
            f"model_describe carried no `model` block; payload keys were "
            f"{sorted(payload)}")
    absent = [key for key in PROOF_KEYS if key not in model]
    if absent:
        raise ModelUnreadable(
            f"model_describe`s `model` block is missing {absent}, so a "
            f"read-back would report a clean model by finding nothing")
    return {
        "unreachable_declarations": list(model.get("unreachable_declarations") or []),
        "unread_fields": list(model.get("unread_fields") or []),
        # Present only when the loader dropped something, so its absence is
        # not a structural problem the way the two above would be.
        "dropped_declarations": list(model.get("dropped_declarations") or []),
        "entity_types": list(model.get("entity_types") or []),
        "indicators": dict(model.get("indicators") or {}),
    }
